# Generated by Django 4.1 on 2022-08-30 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_etudiant', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Etudiant',
        ),
    ]
