# Generated by Django 4.1 on 2022-08-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_etudiant', '0002_delete_etudiant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=32)),
                ('prenom', models.CharField(max_length=32)),
                ('date_naissance', models.DateField()),
                ('faculte', models.CharField(max_length=25)),
                ('genre_etudiant', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=10)),
            ],
        ),
    ]
