# Generated by Django 4.1 on 2022-08-30 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_agence', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_commune', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_province', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_zone', models.CharField(max_length=32)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacie_app.commune')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_stock', models.CharField(max_length=32)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie_app.agence')),
            ],
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_quartier', models.CharField(max_length=32)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacie_app.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_produit', models.CharField(max_length=40)),
                ('prix_achat', models.IntegerField(default=0)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie_app.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_personnel', models.CharField(max_length=32)),
                ('prenom_personnel', models.CharField(max_length=32)),
                ('phone_personnel', models.CharField(max_length=32)),
                ('sexe', models.CharField(max_length=10)),
                ('cni', models.CharField(max_length=32)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacie_app.agence')),
            ],
        ),
        migrations.AddField(
            model_name='commune',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacie_app.province'),
        ),
        migrations.AddField(
            model_name='agence',
            name='quartier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie_app.quartier'),
        ),
    ]
