# Generated by Django 4.1 on 2022-08-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie_app', '0002_client_mutuelle_vente_dette'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='cni',
            new_name='nom_client',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='nom_personnel',
            new_name='phone_client',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='phone_personnel',
            new_name='prenom_client',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='sexe',
            new_name='sexe_client',
        ),
        migrations.RemoveField(
            model_name='client',
            name='prenom_personnel',
        ),
        migrations.AddField(
            model_name='client',
            name='cni_client',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='payercash',
            field=models.IntegerField(default=0),
        ),
    ]
