# Generated by Django 4.1 on 2022-09-01 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie_app', '0006_produit_date_expiration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produit',
            new_name='Medicament',
        ),
        migrations.RenameField(
            model_name='medicament',
            old_name='nom_produit',
            new_name='nom_du_medicament',
        ),
        migrations.RenameField(
            model_name='vente',
            old_name='produit',
            new_name='medicament',
        ),
    ]
