# Generated by Django 4.1 on 2022-09-01 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie_app', '0007_rename_produit_medicament_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_produit', models.CharField(max_length=40)),
                ('prix_achat', models.IntegerField(default=0)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie_app.stock')),
            ],
        ),
        migrations.RenameField(
            model_name='client',
            old_name='nom_client',
            new_name='cni',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='phone_client',
            new_name='nom_personnel',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='prenom_client',
            new_name='phone_personnel',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cni_client',
        ),
        migrations.RemoveField(
            model_name='client',
            name='sexe_client',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='medicament',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='payercash',
        ),
        migrations.AddField(
            model_name='client',
            name='prenom_personnel',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='sexe',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personnel',
            name='sexe',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Medicament',
        ),
        migrations.AddField(
            model_name='vente',
            name='produit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pharmacie_app.produit'),
            preserve_default=False,
        ),
    ]
