# Generated by Django 4.1 on 2022-08-25 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=64)),
                ('volHoraire', models.PositiveIntegerField()),
                ('prof', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=32)),
                ('prenom', models.CharField(max_length=32)),
                ('datenaissane', models.DateField()),
                ('sexe', models.CharField(max_length=2)),
                ('autres', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cours', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etudiant.cours')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.eleve')),
            ],
        ),
    ]
