# Generated by Django 4.1 on 2022-08-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eleve',
            old_name='datenaissane',
            new_name='datenaissance',
        ),
        migrations.AddField(
            model_name='point',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
